# Generated by Django 6.0 on 2026-01-06 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('career', models.CharField(max_length=100)),
                ('match', models.IntegerField()),
                ('required_skills', models.JSONField()),
                ('missing_skills', models.JSONField()),
                ('salary', models.CharField(max_length=100)),
                ('growth', models.CharField(max_length=100)),
                ('growth_percent', models.IntegerField()),
                ('icon', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCareerInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('education', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('expert_skills', models.TextField()),
                ('intermediate_skills', models.TextField()),
                ('soft_skills', models.TextField()),
                ('interests', models.TextField()),
                ('personality', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
