# Generated by Django 6.0 on 2026-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercareerinput',
            name='education',
        ),
        migrations.RemoveField(
            model_name='usercareerinput',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='careeranalysis',
            name='career',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='careeranalysis',
            name='growth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careeranalysis',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careeranalysis',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careeranalysis',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercareerinput',
            name='expert_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercareerinput',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercareerinput',
            name='intermediate_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercareerinput',
            name='personality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercareerinput',
            name='soft_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
