# Generated by Django 6.0 on 2026-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_analysis', '0002_remove_usercareerinput_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercareerinput',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercareerinput',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
